---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(tibble)
library(dplyr)
library(ggplot2)
library(ggnewscale)
# devtools::load_all()
```

## Example

Here is a test example to make sure everything is working still.

```{r}
tib <- tibble(x = c("A", "A", "B"),
              y = c("B", "C", "C"),
              val_1 = c(1, 2, 3),
              val_2 = c(0.2, -0.4, 1.3))
g <- ggplot(tib) +
    geom_tile(aes(x = x, y = y, fill = val_1)) +
    scale_fill_gradient(low = "lightblue1", high = "dodgerblue") +
    new_scale_fill() +
    geom_tile(aes(x = y, y = x, fill = val_2)) +
    scale_fill_gradient(low = "lightpink", high = "tomato")
plot(g)
```

Inspection of `g` (`ggplot` object)

```{r}
g$layers
```

```{r}
for (i in 1:2) print(g$scales$scales[[i]]$aesthetics)

```

```{r}
g$labels
```

Inspection of `ggplot_build(g)` (`ggplot_built` object)

```{r}
gb <- ggplot_build(g)
gb$data
```

```{r}
gb$layout
```

```{r}
gb$plot$scales
```


